ELASTIC_CLUSTER = 'semantic-search:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJDUxZDAzZGQxYmQyYjQxNWM5ODljYzNiYjYwOWRhOTQ3JGNlNjZkYzdlYzM0YzQxYzhiMGUzMWRlNjM3MjEyYzMz'
ELASTIC_USER = 'elastic'
ELASTIC_PASSWORD = '6P32yTc1YFFQTMaTfxHf63DH'

TRANSFORMER_MODEL = 'multi-qa-distilbert-cos-v1'
